"""empty message

Revision ID: e0e29f09eb99
Revises: b0c948ae2e6a
Create Date: 2024-12-27 13:54:41.385124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e29f09eb99'
down_revision = 'b0c948ae2e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('avatar')
        batch_op.drop_column('salt')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    op.drop_table('todos')
    # ### end Alembic commands ###
